---
- name: Install MySQL Server
  ansible.builtin.apt:
    name: mysql-server
    state: present
    update_cache: true

- name: Ensure MySQL service is started
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true
