apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app-service
  name: app-service
spec:
  ports:
  - name: 7000-5000
    port: 7000
    protocol: TCP
    targetPort: 5000
  selector:
    run: my-app
  type: ClusterIP
status:
  loadBalancer: {}
