apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: db-service
  name: db-service
spec:
  ports:
  - name: 8000-3306
    port: 8000
    protocol: TCP
    targetPort: 3306
  selector:
    run: my-app
  type: ClusterIP
status:
  loadBalancer: {}
