apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-app-deployment
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: my-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: my-app
      name: my-app
    spec:
      containers:
      - image: mysql:lts
        name: mysql-db-container
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_PASSWORD
        resources: {}
      - name: flask-app-container
        image: abdelrahman495/simple-flask-app:0.2
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: development
status: {}
