apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql-db
  name: mysql-db
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: my_p@ss123
    image: mysql:lts
    name: mysql-db
    ports:
    - containerPort: 3306
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
