---
# tasks file for node_exporter
- name: Create prometheus user
  ansible.builtin.user:
    name: prometheus
    shell: /bin/bash

- name: Copy SSH configuration to prometheus user
  ansible.builtin.copy:
    src: /home/ubuntu/.ssh
    dest: /home/prometheus/
    remote_src: true
    mode: preserve
    owner: prometheus
    group: prometheus

- name: Create .local/bin directory for prometheus user
  ansible.builtin.file:
    path: /home/prometheus/.local/bin/
    state: directory
    mode: "0775"
    owner: prometheus
    group: prometheus

- name: Download and extract node_exporter binary
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-amd64.tar.gz
    dest: /home/prometheus/.local/bin/
    remote_src: true
    owner: prometheus
    group: prometheus
    extra_opts:
      - --strip-components=1

- name: Create .config/systemd/user/ directory for prometheus user
  ansible.builtin.file:
    path: /home/prometheus/.config/systemd/user/
    state: directory
    mode: "0775"
    owner: prometheus
    group: prometheus

- name: Deploy node_exporter service file from template
  ansible.builtin.template:
    src: service_name.service.j2
    dest: /home/prometheus/.config/systemd/user/node_exporter.service
    owner: prometheus
    group: prometheus
    mode: "0664"

- name: Enable linger for prometheus user
  ansible.builtin.command:
    cmd: loginctl enable-linger prometheus
  register: loginctl_output
  changed_when: loginctl_output.rc != 0

- name: Get UID of prometheus user
  ansible.builtin.command: id -u prometheus
  register: prometheus_uid
  changed_when: false

- name: Start and enable node_exporter service for prometheus user
  ansible.builtin.systemd_service:
    name: node_exporter.service
    state: started
    enabled: true
    daemon_reload: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ prometheus_uid.stdout }}"
  remote_user: prometheus
  become: false
